### PR TITLE
NuGet package fix

### PR DESCRIPTION
**Pull request by azeno**
Some tweaks to get working nuget package

Use `Pack` command on VL.Audio.LTC project (right click on it) inside VS to create the nuget in pkg folder. Tested locally in vvvv 6.2 with `nuget install VL.Audio.LTC -source LOCAL\PATH;nuget.org` and subsequent export was tested by adding the LOCAL\PATH to the generated nuget.config file. Both at runtime as well as in export it was working.

### CODE REVIEW

**Comment by bj-rn** [comment]
Thanks a lot!  But tbh the second part about LOCAL/PATH I don't get at all.

**Comment by azeno** [comment]
The path on your disk to the folder where the generated package is. As long as the package is not uploaded to nuget.org it's the only way to test it.

**Comment by bj-rn** [comment]
Ah ok, since it was all caps, I thought something concerning the windows PATH variable.

**Comment by bj-rn** [comment]
Ok it works now but why? The installed nuget looks like this:
image
image
image

What makes the difference to the "[normal vvvv library workflow"](https://thegraybook.vvvv.org/reference/extending/creating.html) is the nuget package inside the folder. If it is added to the repo like this:
image

and vvvv started with:
`start D:\vvvv\vvvv_gamma_6.2\vvvv.exe --package-repositories D:\_dev\_vl-libs\ --export-package-sources D:\_dev\_vl-libs\ `

runtime works and exporting incl. copying _Ijwhost.dll_ works  too. 

Seems vvvv installs that package into the standard nuget folder upon exporting.

Still this whole thing is kinda cumbersome for development/testing. 

Wondering what would be the way if this whole thing wasn't a nuget but something I just want to use locally / in a project?
I'd always have to copy _Ijwhost_ manually when exporting my application?

**Comment by azeno** [comment]
I'm not sure what you're asking honestly. The whole LOCAL/PATH thing was only a hint for you to test before uploading it to nuget.org - or in the future how to be able to test such things. And yes that projects and packages are fundamentally different is a huge pain in .NET. Super hard to get it right, especially if both workflows (from source or from nuget.org) shall be supported.

Why the .NET runtime is not able to resolve that Ijwhost.dll by its own is a mystery to me as well.

**Comment by bj-rn** [comment]
> I'm not sure what you're asking honestly

Not sure myself :) more like thinking aloud and wondering what's the best workflow...

**Pull request merged**
